---
- name: add nginx repository
  apt_repository: repo=ppa:nginx/stable
  tags: nginx

- name: install nginx
  apt: pkg=nginx update_cache=yes state=latest
  tags: nginx

- name: write nginx default config
  copy: src=default dest=/etc/nginx/sites-available/default mode=0644
  tags: nginx
  notify:
    - restart nginx
